export type EmbedServer = {
  id: string;
  name: string;
  enabled: boolean;
  domains: string[];
  idTypes: ('tmdb' | 'imdb' | 'anilist' | 'mal')[];
  movieTemplate: string;
  tvTemplate: string;
  animeTemplate?: string | null;
  defaultParams?: Record<string, string>;
  docs?: string;
};

/** Full catalog — all documented + researched providers from streamingapilinks.md */
export const EMBED_SERVER_CATALOG: EmbedServer[] = [
  {
    id: '111movies',
    name: '111Movies',
    enabled: true,
    domains: ['111movies.net'],
    idTypes: ['tmdb', 'imdb'],
    movieTemplate: 'https://111movies.net/movie/{id}',
    tvTemplate: 'https://111movies.net/tv/{id}/{season}/{episode}',
    docs: 'https://111movies.net/',
  },
  {
    id: '1embed',
    name: '1Embed',
    enabled: true,
    domains: ['1embed.cc'],
    idTypes: ['tmdb', 'imdb'],
    movieTemplate: 'https://1embed.cc/embed/movie/{id}',
    tvTemplate: 'https://1embed.cc/embed/tv/{id}/{season}/{episode}',
    docs: 'https://1embed.cc/',
  },
  {
    id: '2embed',
    name: '2Embed',
    enabled: true,
    domains: ['www.2embed.cc', 'www.2embed.skin', '2embed.stream', '2embed.skin'],
    idTypes: ['tmdb', 'imdb'],
    movieTemplate: 'https://www.2embed.cc/embed/{id}',
    tvTemplate: 'https://www.2embed.cc/embedtv/{id}?s={season}&e={episode}',
    docs: 'https://www.2embed.cc/',
  },
  {
    id: 'autoembed',
    name: 'AutoEmbed',
    enabled: true,
    domains: ['player.autoembed.app', 'autoembed.app'],
    idTypes: ['tmdb', 'imdb'],
    movieTemplate: 'https://player.autoembed.app/embed/movie/{id}',
    tvTemplate: 'https://player.autoembed.app/embed/tv/{id}/{season}/{episode}',
    docs: 'https://autoembed.app/',
  },
  {
    id: 'cinemaos',
    name: 'CinemaOS',
    enabled: true,
    domains: ['cinemaos.tech'],
    idTypes: ['tmdb'],
    movieTemplate: 'https://cinemaos.tech/player/{tmdbId}',
    tvTemplate: 'https://cinemaos.tech/player/{tmdbId}/{season}/{episode}',
    docs: 'https://cinemaos.tech/embed',
  },
  {
    id: 'cinesrc',
    name: 'CineSrc',
    enabled: true,
    domains: ['cinesrc.st'],
    idTypes: ['tmdb'],
    movieTemplate: 'https://cinesrc.st/embed/movie/{tmdbId}',
    tvTemplate: 'https://cinesrc.st/embed/tv/{tmdbId}?s={season}&e={episode}',
    docs: 'https://cinesrc.st/',
  },
  {
    id: 'cinezo',
    name: 'Cinezo',
    enabled: true,
    domains: ['player.cinezo.live', 'cinezo.live'],
    idTypes: ['tmdb', 'anilist'],
    movieTemplate: 'https://player.cinezo.live/embed/movie/{tmdbId}',
    tvTemplate: 'https://player.cinezo.live/embed/tv/{tmdbId}/{season}/{episode}',
    animeTemplate: 'https://player.cinezo.live/embed/anime/{anilistId}/{episode}?dub=false',
    docs: 'https://cinezo.live/',
  },
  {
    id: 'icefy',
    name: 'Icefy',
    enabled: true,
    domains: ['embed.icefy.top'],
    idTypes: ['tmdb', 'imdb'],
    movieTemplate: 'https://embed.icefy.top/movie/{id}',
    tvTemplate: 'https://embed.icefy.top/tv/{id}/{season}/{episode}',
    docs: 'https://embed.icefy.top/',
  },
  {
    id: 'mapple',
    name: 'MappleTV',
    enabled: true,
    domains: ['mappletv.uk', 'mapple.uk'],
    idTypes: ['tmdb'],
    movieTemplate: 'https://mappletv.uk/watch/movie/{tmdbId}',
    tvTemplate: 'https://mappletv.uk/watch/tv/{tmdbId}-{season}-{episode}',
    docs: 'https://mappletv.uk/',
  },
  {
    id: 'nontongo',
    name: 'NontonGo',
    enabled: true,
    domains: ['nontongo.win'],
    idTypes: ['tmdb', 'imdb'],
    movieTemplate: 'https://nontongo.win/embed/movie/{id}',
    tvTemplate: 'https://nontongo.win/embed/tv/{id}/{season}/{episode}',
    docs: 'https://nontongo.win/',
  },
  {
    id: 'nxsha',
    name: 'Nxsha',
    enabled: true,
    domains: ['web.nxsha.app'],
    idTypes: ['tmdb', 'imdb'],
    movieTemplate: 'https://web.nxsha.app/embed/movie/{id}',
    tvTemplate: 'https://web.nxsha.app/embed/tv/{id}/{season}/{episode}',
    docs: 'https://web.nxsha.app/embed',
  },
  {
    id: 'peachify',
    name: 'Peachify',
    enabled: true,
    domains: ['peachify.top'],
    idTypes: ['tmdb', 'imdb'],
    movieTemplate: 'https://peachify.top/embed/movie/{id}',
    tvTemplate: 'https://peachify.top/embed/tv/{id}/{season}/{episode}',
    docs: 'https://peachify.top/',
  },
  {
    id: 'primesrc',
    name: 'PrimeSrc',
    enabled: true,
    domains: ['primesrc.me'],
    idTypes: ['tmdb', 'imdb'],
    movieTemplate: 'https://primesrc.me/embed/movie?tmdb={tmdbId}',
    tvTemplate: 'https://primesrc.me/embed/tv?tmdb={tmdbId}&season={season}&episode={episode}',
    docs: 'https://primesrc.me/',
  },
  {
    id: 'smashystream',
    name: 'SmashyStream',
    enabled: true,
    domains: ['player.smashystream.com', 'player.smashy.stream'],
    idTypes: ['tmdb', 'imdb'],
    movieTemplate: 'https://player.smashystream.com/movie/{id}',
    tvTemplate: 'https://player.smashystream.com/tv/{id}?s={season}&e={episode}',
    docs: 'https://player.smashystream.com/',
  },
  {
    id: 'spencerdevs',
    name: 'SpenEmbed',
    enabled: true,
    domains: ['spencerdevs.xyz'],
    idTypes: ['tmdb', 'anilist'],
    movieTemplate: 'https://spencerdevs.xyz/movie/{tmdbId}',
    tvTemplate: 'https://spencerdevs.xyz/tv/{tmdbId}/{season}/{episode}',
    animeTemplate: 'https://spencerdevs.xyz/anime/{anilistId}/{episode}',
    docs: 'https://spencerdevs.xyz/',
  },
  {
    id: 'streamvault',
    name: 'StreamVault',
    enabled: true,
    domains: ['streamvaultsrc.click'],
    idTypes: ['tmdb', 'imdb'],
    movieTemplate: 'https://streamvaultsrc.click/embed/movie/{id}',
    tvTemplate: 'https://streamvaultsrc.click/embed/tv/{id}/{season}/{episode}',
    docs: 'https://streamvaultsrc.click/',
  },
  {
    id: 'superembed',
    name: 'SuperEmbed',
    enabled: true,
    domains: ['multiembed.mov', 'www.superembed.stream'],
    idTypes: ['tmdb', 'imdb'],
    movieTemplate: 'https://multiembed.mov/?video_id={id}&tmdb=1',
    tvTemplate: 'https://multiembed.mov/?video_id={id}&tmdb=1&s={season}&e={episode}',
    docs: 'https://www.superembed.stream/',
  },
  {
    id: 'thisiscinema',
    name: 'ThisIsCinema',
    enabled: true,
    domains: ['thisiscinema.pages.dev'],
    idTypes: ['tmdb', 'imdb'],
    movieTemplate: 'https://thisiscinema.pages.dev/embed/movie/{id}',
    tvTemplate: 'https://thisiscinema.pages.dev/embed/tv/{id}/{season}/{episode}',
    docs: 'https://thisiscinema.pages.dev/',
  },
  {
    id: 'vidapi',
    name: 'VidAPI',
    enabled: true,
    domains: ['vidapi.xyz', 'vidapi.ru'],
    idTypes: ['tmdb', 'imdb'],
    movieTemplate: 'https://vidapi.xyz/embed/movie/{id}',
    tvTemplate: 'https://vidapi.xyz/embed/tv/{id}/{season}/{episode}',
    docs: 'https://vidapi.xyz/',
  },
  {
    id: 'videasy',
    name: 'Videasy',
    enabled: true,
    domains: ['player.videasy.net', 'www.videasy.net'],
    idTypes: ['tmdb', 'anilist'],
    movieTemplate: 'https://player.videasy.net/movie/{tmdbId}',
    tvTemplate: 'https://player.videasy.net/tv/{tmdbId}/{season}/{episode}',
    animeTemplate: 'https://player.videasy.net/anime/{anilistId}/{episode}',
    docs: 'https://www.videasy.net/docs',
  },
  {
    id: 'vidfast',
    name: 'VidFast',
    enabled: true,
    domains: ['vidfast.pro', 'vidfast.xyz', 'vidfast.pm', 'vidfast.net', 'vidfast.me', 'vidfast.io', 'vidfast.in'],
    idTypes: ['tmdb', 'imdb'],
    movieTemplate: 'https://vidfast.pro/movie/{id}',
    tvTemplate: 'https://vidfast.pro/tv/{id}/{season}/{episode}',
    defaultParams: { autoPlay: 'true' },
    docs: 'https://vidfast.pro/',
  },
  {
    id: 'vidflix',
    name: 'VidFlix',
    enabled: true,
    domains: ['vidflix.club'],
    idTypes: ['tmdb'],
    movieTemplate: 'https://vidflix.club/movie/{tmdbId}',
    tvTemplate: 'https://vidflix.club/tv/{tmdbId}/{season}/{episode}',
    docs: 'https://vidflix.club/',
  },
  {
    id: 'vidify',
    name: 'Vidify',
    enabled: true,
    domains: ['player.vidify.top', 'vidify.top'],
    idTypes: ['tmdb', 'anilist'],
    movieTemplate: 'https://player.vidify.top/embed/movie/{tmdbId}',
    tvTemplate: 'https://player.vidify.top/embed/tv/{tmdbId}/{season}/{episode}',
    animeTemplate: 'https://player.vidify.top/embed/anime/{anilistId}/{episode}',
    docs: 'https://vidify.top/',
  },
  {
    id: 'vidjoy',
    name: 'VidJoy',
    enabled: true,
    domains: ['vidjoy.pro'],
    idTypes: ['tmdb'],
    movieTemplate: 'https://vidjoy.pro/embed/movie/{tmdbId}',
    tvTemplate: 'https://vidjoy.pro/embed/tv/{tmdbId}/{season}/{episode}',
    docs: 'https://vidjoy.pro/embed/doc',
  },
  {
    id: 'vidking',
    name: 'VidKing',
    enabled: true,
    domains: ['www.vidking.net', 'vidking.net'],
    idTypes: ['tmdb', 'imdb'],
    movieTemplate: 'https://www.vidking.net/embed/movie/{id}',
    tvTemplate: 'https://www.vidking.net/embed/tv/{id}/{season}/{episode}',
    docs: 'https://www.vidking.net/',
  },
  {
    id: 'vidlink',
    name: 'VidLink',
    enabled: true,
    domains: ['vidlink.pro'],
    idTypes: ['tmdb', 'mal'],
    movieTemplate: 'https://vidlink.pro/movie/{tmdbId}',
    tvTemplate: 'https://vidlink.pro/tv/{tmdbId}/{season}/{episode}',
    animeTemplate: 'https://vidlink.pro/anime/{malId}/{episode}/sub',
    docs: 'https://vidlink.pro/',
  },
  {
    id: 'vidnest',
    name: 'VidNest',
    enabled: true,
    domains: ['vidnest.fun'],
    idTypes: ['tmdb', 'anilist'],
    movieTemplate: 'https://vidnest.fun/movie/{tmdbId}',
    tvTemplate: 'https://vidnest.fun/tv/{tmdbId}/{season}/{episode}',
    animeTemplate: 'https://vidnest.fun/anime/{anilistId}/{episode}/sub',
    docs: 'https://vidnest.fun/',
  },
  {
    id: 'vidplays',
    name: 'VidPlays',
    enabled: true,
    domains: ['vidplays.fun'],
    idTypes: ['tmdb'],
    movieTemplate: 'https://vidplays.fun/embed/movie/{tmdbId}',
    tvTemplate: 'https://vidplays.fun/embed/tv/{tmdbId}/{season}/{episode}',
    docs: 'https://vidplays.fun/',
  },
  {
    id: 'vidplus',
    name: 'VidPlus',
    enabled: true,
    domains: ['vidplus.to', 'player.vidplus.to'],
    idTypes: ['tmdb', 'anilist'],
    movieTemplate: 'https://player.vidplus.to/embed/movie/{tmdbId}',
    tvTemplate: 'https://player.vidplus.to/embed/tv/{tmdbId}/{season}/{episode}',
    animeTemplate: 'https://player.vidplus.to/embed/anime/{anilistId}/{episode}',
    docs: 'https://vidplus.to/',
  },
  {
    id: 'vidrock',
    name: 'VidRock',
    enabled: true,
    domains: ['vidrock.ru'],
    idTypes: ['tmdb', 'imdb'],
    movieTemplate: 'https://vidrock.ru/movie/{id}',
    tvTemplate: 'https://vidrock.ru/tv/{id}/{season}/{episode}',
    docs: 'https://vidrock.ru/',
  },
  {
    id: 'vidsrc',
    name: 'VidSrc',
    enabled: true,
    domains: ['vidsrc.to', 'vidsrc.su', 'vidsrc.vip', 'vidsrc.rip', 'www.vidsrc.wtf', 'vidsrcme.ru', 'vidsrc-me.ru', 'vidsrc-me.su', 'vsembed.ru'],
    idTypes: ['tmdb', 'imdb'],
    movieTemplate: 'https://vidsrc.to/embed/movie/{id}',
    tvTemplate: 'https://vidsrc.to/embed/tv/{id}/{season}/{episode}',
    docs: 'https://vidsrc.to/',
  },
  {
    id: 'vidsync',
    name: 'VidSync',
    enabled: true,
    domains: ['vidsync.xyz'],
    idTypes: ['tmdb', 'imdb'],
    movieTemplate: 'https://vidsync.xyz/embed/movie/{id}',
    tvTemplate: 'https://vidsync.xyz/embed/tv/{id}/{season}/{episode}',
    docs: 'https://vidsync.xyz/',
  },
  {
    id: 'vidup',
    name: 'VidUp',
    enabled: true,
    domains: ['vidup.to'],
    idTypes: ['tmdb', 'imdb'],
    movieTemplate: 'https://vidup.to/embed/{id}',
    tvTemplate: 'https://vidup.to/embed/tv/{id}/{season}/{episode}',
    docs: 'https://vidup.to/',
  },
  {
    id: 'vidzee',
    name: 'VidZee',
    enabled: true,
    domains: ['player.vidzee.wtf', 'vidzee.wtf'],
    idTypes: ['tmdb'],
    movieTemplate: 'https://player.vidzee.wtf/embed/movie/{tmdbId}',
    tvTemplate: 'https://player.vidzee.wtf/embed/tv/{tmdbId}/{season}/{episode}',
    docs: 'https://vidzee.wtf/',
  },
  {
    id: 'vidzen',
    name: 'VidZen',
    enabled: true,
    domains: ['vidzen.fun'],
    idTypes: ['tmdb'],
    movieTemplate: 'https://vidzen.fun/movie/{tmdbId}',
    tvTemplate: 'https://vidzen.fun/tv/{tmdbId}/{season}/{episode}',
    docs: 'https://vidzen.fun/',
  },
  {
    id: 'vidcore',
    name: 'VidCore',
    enabled: true,
    domains: ['vidcore.net'],
    idTypes: ['tmdb', 'imdb'],
    movieTemplate: 'https://vidcore.net/embed/movie/{id}',
    tvTemplate: 'https://vidcore.net/embed/tv/{id}/{season}/{episode}',
    docs: 'https://vidcore.net/',
  },
  {
    id: 'vixsrc',
    name: 'VixSrc',
    enabled: true,
    domains: ['vixsrc.to'],
    idTypes: ['tmdb', 'imdb'],
    movieTemplate: 'https://vixsrc.to/movie/{id}',
    tvTemplate: 'https://vixsrc.to/tv/{id}/{season}/{episode}',
    docs: 'https://vixsrc.to/',
  },
  {
    id: 'wfs',
    name: 'WatchFreeStreams',
    enabled: true,
    domains: ['embed.wfs.lol', 'wfs.lol'],
    idTypes: ['tmdb'],
    movieTemplate: 'https://embed.wfs.lol/embed/movie/{tmdbId}',
    tvTemplate: 'https://embed.wfs.lol/embed/tv/{tmdbId}/{season}/{episode}',
    docs: 'https://wfs.lol/embed-api',
  },
];
